# Abstract

This study examines the effect of active listening on perceptions of leaders. It is based on the knowledge that emotional intelligence is a fundamental component to good leadership and competent listening skills are central to demonstrating this form of intelligence. Research from multiple domains has shown that active listening leads to more positive perceptions, enhanced perspective-taking, and reductions in intergroup conflict. Because such outcomes are often associated with successful leaders, I hypothesized that leaders who demonstrate active listening would be perceived more favorably than leaders who do not. Participants were presented with two vignettes: one a professor and the other a business manager. The vignettes were created to show active listening, inactive listening, or information without interaction. Ratings were then completed on each leader. Preliminary data support the claim that leaders are perceived more favorably when they demonstrate active listening. 

## Subheading 2


Keywords: active listening, emotional intelligence, leadership
\newpage