# Methods

*Participants*

|       Data was collected from Seton Hall Undergraduate students, who were recruited through Seton Hall University SONA system. Participants received extra credit in their class for participation. All participants were asked to bring their laptops in order to complete the experiment. Our sample size consisted of 86 students. Sixty-six of the participants were female, and the other 20 were male. Students' academic year broke down as follow: forty-eight Freshmen, twenty-six Sophomores, eleven Juniors, and one Senior. Also, the average participants' age was approximately 19.1 (SD=1.09). Participants' race consists of 37 White, 22 Hispanic/Latino, 18 Asian, and 7 Black or African American. Participants were also asked if they worked or not, and 50 participants had a job, and 36 participants did not have a job. More specifically, 3 participants had a full-time job, 32 participants had part-time jobs, and 15 participants work intermittently. 

*Materials*

|      There were six vignettes created for this study. The vignettes were about two different leaders (manager, professor). The vignettes portrayed demonstrated the leader's listening skills (Active Listening, Gives out Orders, Control Condition) in a workplace or a classroom. Participants read two vignettes about one type of leader's listening skills on both the manager and professor. In the Active Listening condition, Professor N takes the time to listen to the students' concerns, ask for feedback, and solve any problems that the students addressed with the class. In the Giving out Order or Inactive Listening condition, Professor N explains the course to the students, and ask for feedback, when the student express their concerns. The professor does not acknowledge their concerns and continues by explaining the course. In the control condition, Professor N does not show any listening skills and does not engage with the students for feedback, and Professor N explains what point after the other. Participants were randomly assigned to one of three conditions and randomly assigned to the order in which leader they read about first the manager or professor. 

*Perception Ratings*

|       Participants' perceptions concerning the leaders' listening skills were obtained using a survey. The survey commenced with a statement asking the participant to rate the items. The survey was a 7-point Likert scale, which measured the leader's listening skills, communication skills, and emotional intelligence. The endpoints of the scales were labeled (1= Strongly Disagree with the statement, and 7= Strongly Agree with the statement). 

*Procedure*

|       Participants were randomly assigned to a condition using a random number generator. The participant received an email with a link to the experiment. Once participants open the experiment, they read the instructions for the experiment and started reading the first vignette. After the first vignette, participants rated their perceptions on the first leader on the 1-7 scales, and the participant was asked if the leader is good, open to change, communicate well, etc. Next, the participants read the second vignette on the second leader. The participants rated their perception again on a 1-7 scale using similar statements as on the previous leader. After the participants finish the experiment, they were debriefed about the experiment. 
 